status-im/nim-web3

web3.nim, web3/conversions.nim
Infura doesn't like block numbers appearing as regular JavaScript literals in the JSON. It reports the following error:
```
{"code":-32602,"message":"invalid argument 0: hex string without 0x prefix"}
```
The solution is to hex-encode all block numbers.
=> More hot fixes for Infura compatiblity

web3.nim
Previously, generated contract types and supporting methods were not exported and could not be used outside of the module declaring the contract without explicitly exporting each contract type and method. This PR exports the contract type definition and all contract methods.
=> feat: export generated contracts and methods

web3/ethcallsigs.nim
Message to sign should be sent as a DATA hex string, not a JSON array of numbers.
Before this change, calling web3.provider.eth_sign would cause the following error in Ganache:
```
eth_sign
Errors encountered in param 1: Invalid value [16,42,44,179,215,214,129,238,17,235,124,244,129,235,30,58,104,127,165,149,111,61,132,239,253,29,124,22,224,54,159,115] supplied to : DATA
```
See also: https://eth.wiki/json-rpc/API#eth_sign
=> Fix signature of eth_sign

tests/all_tests.nim, tests/test.nim, tests/test_quantity.nim, tests/test_utils.nim, web3/confutils_defs.nim, web3/conversions.nim, web3/encoding.nim, web3/engine_api.nim, web3/ethhexstrings.nim, web3/ethtypes.nim, web3/transaction_signing.nim
- `proc` to `func`
- remove some `result` usage
- add tests for `Quantity` parsing
- address https://github.com/status-im/nimbus-eth2/issues/3844
=> enforce JSON-RPC Quantity spec syntax rules

tests/test_ethhexstrings.nim, web3/conversions.nim, web3/ethcallsigs.nim, web3/ethhexstrings.nim, web3/ethtypes.nim
- Add `get_Proof` client call (https://eips.ethereum.org/EIPS/eip-1186)
- Fixes bug in `hexstrings` which did not allow `0x0` hex.
=> Add client for eth_getProof

web3/ethtypes.nim
* hashes are not `uint256` - they should not have leading zeroes stripped for example
* difficulty can be >uint64.high
* block nonce is not a quantity
=> fix block field types

tests/test_ethhexstrings.nim, web3/ethhexstrings.nim
It should be possible to have empty hex data string, for exemple when returning response for `eth_getCode` request for user controlled account
=> Handle empty data hex string

web3/ethcallsigs.nim, web3/ethtypes.nim
Small pr to add `eth_createAccessList` to client.
Initially I also wanted to fix `EthCall` and `EthSend` objects as those are super outdated and wrong (`gasPrice` as `int`) but this turned out to be bit bigger change so it is better to do it in separate pr.
=> Add create access list call to client

web3/ethtypes.nim
It appears gnosis publishes both nonce and mixhash these days, looking
at `curl https://rpc.gnosischain.com/   -X POST   -H "Content-Type:
application/json"   --data
'{"method":"eth_getBlockByNumber","params":["0x18c97c0",false],"id":1,"jsonrpc":"2.0"}'
| jq`
=> remove `gnosisChainBinary` hack

web3/engine_api.nim, web3/engine_api_callsigs.nim, web3/engine_api_types.nim
A follow-up of sorts to https://github.com/status-im/nim-web3/pull/77
It might be that `nimbus-eth1` indeed requires a signature for this `getPayloadV2` call which has this ambiguous return value. `nimbus-eth2` does not require or benefit from such a call.
Therefore, it's reasonable to have both. Whatever other cleanups or modifications occur, it will remain useful for `nimbus-eth2` to be able to call this RPC and use the RPC framework to validate the exact payload type it's expecting, rather than having to do so ad-hoc separately.
=> re-add GetPayload v2 return type actually constrained to v2

web3/engine_api_callsigs.nim, web3/engine_api_types.nim, web3/ethtypes.nim
Updates nim-web3 to the changes from https://github.com/ethereum/execution-apis/pull/402.
=> Update EIP4844 types

web3/ethtypes.nim
JSON-RPC also returns `mixHash` and `withdrawals` when querying `eth_getBlockByHash` et al. Expose them in `BlockObject` as well.
=> add `mixHash`, `withdrawals` fields to `BlockObject`

web3/ethtypes.nim
Correct `TransactionObject` types to `Quantity`, `source` to `from`, and add missing fields for parsing JsonRPC up through EIP-1559. EIP-4844 still missing.
=> fix `TransactionObject` type up through mainnet

web3/engine_api_types.nim
See the spec in:
https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_getpayloadbodiesbyhashv1
https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_getpayloadbodiesbyrangev1
=> Change withdrawals field of ExecutionPayloadBodyV1 become optional

web3/conversions.nim
Tag `writeValue` overrides with `{.raises: [IOError].}`.
=> add `{.raises.}` annotation to `writeValue`

web3/ethtypes.nim
Extend `TransactionObject` to parse JSON-RPC response post-EIP-4844 with `maxFeePerBlobGas` and `blobVersionedHashes` fields.
=> add EIP-4844 fields to `TransactionObject`

tests/test.nim, web3/ethtypes.nim
Extend `ReceiptObject` and `LogObject` according to documentation at:
- https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactionreceipt
- https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getfilterchanges
Also fix the `LogObject` types from `string` to `Quantity`.
=> update `ReceiptObject` and `LogObject`

tests/test.nim, tests/test_deposit_contract.nim, tests/test_logs.nim, web3.nim, web3/confutils_defs.nim
With Nim 1.6, `Defect` does not need to be specified anymore inside `{.raises.}` and triggers redundant `XCannotRaiseY` hints. Remove.
=> replace `{.raises: [Defect].}` with `{.raises: [].}` (Nim 1.6)

web3/ethtypes.nim
https://github.com/ethereum/consensus-specs/pull/3521 renders it unnecessary, because `minimal` and `mainnet` presets share the same fieldElementsPerBlob now to resolve https://github.com/ethereum/consensus-specs/pull/3255 as of https://github.com/ethereum/consensus-specs/releases/tag/v1.4.0-beta.3
=> rm `web3_consensus_const_preset`

web3/primitives.nim
`skip0xPrefix` is no longer used since #108 where its usage was replaced with `stew/byteutils`' hexToSeqByte`.
=> remove unused `skip0xPrefix`

web3/eth_api_types.nim
According to [ETH docs](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call), `EthCall` should have `from` field, instead of `source`.
Fixes #67
=> Fixed source->from field of EthCall

tests/test_execution_types.nim
`blobGasUsed` is listed before `excessBlobGas`. Adjusting the test to use the same field order to make it easier to review (consistency). No semantic changes.
=> Synchronize order of `blobGasUsed` / `excessBlobGas` in test

web3.nim
In #108 a regression got introduced, resulting in `fromBlock`, `toBlock` and `blockHash` no longer being sent when a client calls `eth_getLogs`. This may break the deposits import process in `nimbus-eth2`, resulting in messages such as:
```
ERR 2024-02-06 19:52:34.474+01:00 The Eth1 chain is not synced               ourDepositsCount=0 targetDepositsCount=403
```
Fixing the regression restores successful import messages:
```
INF 2024-02-06 22:12:14.863+01:00 Eth1 sync progress                         topics="elmon" blockNumber=1349452 depositsProcessed=3
```
=> re-add support for `fromBlock`, `toBlock`, `blockHash` in `eth_getLogs`

tests/test_execution_api.nim, tests/test_json_marshalling.nim, web3/eth_api_types.nim
The `error` field of `AccesListResult` is not documented anywhere, probably a mistake when it first introduced in nim-web3. And the execution_api test not detecting this because of a bug in nim-json-serialization `JsonValueRef.Object` comparison.
https://github.com/status-im/nim-json-serialization/pull/88
=> Remove error field from AccessListResult

web3/conversions.nim
As it is also possible to use directly BlockNumber instead of the RtBlockIdentifier in the eth_api.
=> Add writeValue for BlockNumber

tests/test_contracts.nim, tests/test_deposit_contract.nim, tests/test_json_marshalling.nim, tests/test_logs.nim, web3.nim, web3/conversions.nim, web3/eth_api_types.nim, web3/primitives.nim
The `writeValue` added for `BlockNumber` in #136 interferes with other `uint64` because `BlockNumber` is not `distinct`. Marking it `distinct` avoids polluting global serialization logic.
=> make `BlockNumber` `distinct`

tests/helpers/handlers.nim, tests/helpers/utils.nim, tests/test_json_marshalling.nim, tests/test_signed_tx.nim, web3.nim, web3/conversions.nim, web3/engine_api_types.nim, web3/eth_api.nim, web3/eth_api_types.nim, web3/primitives.nim, web3/transaction_signing.nim
see: https://github.com/ethereum/execution-apis/blob/4b225e0d273e92982b2c539d63eaaa756c5285a4/src/schemas/transaction.yaml#L358
The execution-api schema only shows `maxFeePerBlobGas`, `blobVersionedHashes`, and `blobs` of EIP-4844.
But the reference implementation(geth), also have `commitments` and `proofs` fields.
=> Unify EthCall/EthSend into TransactionArgs

tests/helpers/handlers.nim, tests/test_execution_api.nim
- https://github.com/ethereum/execution-apis/releases/tag/v1.0.0-beta.4
This was already partially applied, the following commits were missing:
- update the doc of eth_getBalance to put block as required parameters
- schemas/filter: fixup some bugs in null filter topics and address
- tests: regenerate tests with new rpctestgen chain
- tests: add forkenv.json for hive
- tests: add headfcu.json
- tests: add comments in tests
- Specify Client Versions on Engine API
- Add eth_blobBaseFee; add blobs to eth_feeHistory
- Added engine_getPayloadV4 and engine_newPayloadV4 for Prague
- Update receipt.yaml to title instead of name
- Move EIP-6110 to Prague
- Add EIP-7251 to Prague
- engine: rename for 7002 partial withdrawals and 7685 requests
=> bump `execution-apis` to `v1.0.0-beta.4`

web3/eth_api_types.nim
An individual EIP-4844 transaction can refer to multiple blobs.
=> Allow multiple blobs in `eth_sendTransaction`

tests/helpers/handlers.nim
`eth_sendRawTransaction` uses a `PooledTransaction` not `Transaction`.
=> Use correct type for blob transactions

tests/test_execution_types.nim, web3/conversions.nim, web3/engine_api_types.nim, web3/execution_types.nim
Required for Pectra devnet-1
https://github.com/ethereum/execution-apis/pull/554
=> update Pectra execution API types

tests/test_execution_types.nim, web3/engine_api_types.nim
Required for https://notes.ethereum.org/@ethpandaops/pectra-devnet-1
=> align WithdrawalRequestV1 with EIP-7002 and consensus spec

web3/engine_api.nim
`engine_exchangeTransitionConfigurationV1` **MUST** not  be used anymore by clients,  and `nimbus-eth2` does not use it as of https://github.com/status-im/nimbus-eth2/pull/5889, so remove it.
`nimbus-eth1` can still choose to support it (though, must not require it for Dencun-scheduled networks), so leaving `TransitionConfigurationV1` in place. The removed signature is for client-side calling only, and does not affect `nimbus-eth1`.
https://github.com/ethereum/execution-apis/blob/a0d03086564ab1838b462befbc083f873dcf0c0f/src/engine/cancun.md#deprecate-engine_exchangetransitionconfigurationv1 says:
>  This document introduces deprecation of [`engine_exchangeTransitionConfigurationV1`](./paris.md#engine_exchangetransitionconfigurationv1). The deprecation is specified as follows:
>
> 1. …
=> rm unused engine_exchangeTransitionConfigurationV1 calling signature

tests/test_execution_types.nim, web3/contract_dsl.nim, web3/conversions.nim, web3/encoding.nim, web3/engine_api.nim, web3/engine_api_types.nim, web3/eth_api_types.nim, web3/execution_types.nim
- https://github.com/ethereum/execution-apis/pull/591
=> new Pectra engine API

tests/test_contracts.nim, tests/test_json_marshalling.nim, tests/test_primitives.nim, web3.nim, web3/conversions.nim, web3/eth_api_types.nim
Since both of them now have the same types for their fields, no need to keep separate types for the same thing.
=> Replace AccessTuple with AccessPair from nim-eth

web3.nim, web3/contract_dsl.nim
Surprisingly the pending event bug not detected when using ganache. It only manifest after migrated to hardhat. Also not detected on linux and windows CI. Only on macos amd64 CI, and sometimes on macos arm64 CI. Probably related to async timing trigger pending event?. But it's a genuine bug, dated back far before migration from stdlib/json to json-serialization.
=> Fix subscription handler

nim.cfg, tests/test_contract_dsl.nim, tests/test_logs.nim, web3.nimble, web3/confutils_defs.nim
- Neither `ObservableStores` nor `GcUnsafe2` seems to trigger in either `nimbus-eth1` or `nimbus-eth2`.
- `std/json/` was triggering an `UnusedImport` warning.
- `fromHex(T, string input)` triggers a `ConvFromXtoItselfNotNeeded` hint from `string` to `string`
=> re-enable ObservableStores and GcUnsafe2 warnings

tests/test_json_marshalling.nim, web3/engine_api.nim, web3/engine_api_types.nim, web3/execution_types.nim
Required for https://notes.ethereum.org/@ethpandaops/pectra-devnet-5
=> update to https://github.com/ethereum/execution-apis/pull/599

tests/test_json_marshalling.nim, tests/test_null_conversion.nim, web3/conversions.nim, web3/engine_api_types.nim
Neither `nimbus-eth1` nor `nimbus-eth2` uses it, current CLs are prohibited from using it, and it's deprecated in an EL context.
=> rm unused TransitionConfigurationV1

web3/eth_api_types.nim, web3/transaction_signing.nim
Reverts EIP-7873-specific parts of:
- https://github.com/status-im/nim-web3/pull/198
It has since been [declined for inclusion](https://eips.ethereum.org/EIPS/eip-7607#declined-for-inclusion) in Fusaka.
Depends on:
- https://github.com/status-im/nim-eth/pull/796
=> rm EIP-7873 support

tests/helpers/handlers.nim, tests/helpers/min_blobtx_rlp.nim, web3/conversions.nim
Since PooledTransaction has been removed from nim-eth. We only need a minimum rlp reader to pass the test. And make clear the distinction between PooledTransaction hash and inner tx hash.
=> Replace PooledTransaction usage from test with BlobTx
